version: '3.9'

services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    env_file:
      - src/.env
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
